Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

AllCops:
  SuggestExtensions: false