source "https://rubygems.org"
gem "capybara"
gem "cucumber"
gem "pry"
gem "psych", "~> 4.0"
gem "require_all"
gem "rspec"
gem "rubocop", "~> 1.0", ">= 1.0.0"
gem "rubocop-capybara"
gem "selenium-webdriver"
gem "site_prism"
